version: "3.9"

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  postgres_data:
