# Generated by Django 5.2.1 on 2025-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publish_year",
            field=models.DateField(),
        ),
    ]
