# Generated by Django 5.2.1 on 2025-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0002_alter_book_publish_year"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE book_service_book
                    ALTER COLUMN publish_year TYPE integer
                        USING EXTRACT(YEAR FROM publish_year)::integer;
                """,
            reverse_sql="""
                        ALTER TABLE book_service_book
                            ALTER COLUMN publish_year TYPE date
                                USING TO_DATE(publish_year::text, 'YYYY');
                        """,
        ),
    ]
