# Generated by Django 5.2.1 on 2025-05-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_service", "0003_alter_book_publish_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Книга", "verbose_name_plural": "Книги"},
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publish_year",
            field=models.PositiveIntegerField(verbose_name="Год публикации"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
